apiVersion: v1
kind: Secret
metadata:
  name: mongodb-atlas-secret
type: Opaque
data:
  username: c2FtcGxldXNlcg==    # Base64 encoded username has sampleuser
  password: c2FtcGxlcGFzc3dvcmQ=    # Base64 encoded password has samplepassword

